package org.tricol.supplierchain.enums;

public enum PermissionName {
    FOURNISSEUR_CREATE,
    FOURNISSEUR_UPDATE,
    FOURNISSEUR_DELETE,
    FOURNISSEUR_READ,
    
    PRODUIT_CREATE,
    PRODUIT_UPDATE,
    PRODUIT_DELETE,
    PRODUIT_READ,
    PRODUIT_CONFIGURE_SEUIL,
    
    COMMANDE_CREATE,
    COMMANDE_UPDATE,
    COMMANDE_VALIDATE,
    COMMANDE_CANCEL,
    COMMANDE_RECEIVE,
    COMMANDE_READ,
    
    STOCK_READ,
    STOCK_VALORISATION,
    STOCK_HISTORIQUE,
    
    BON_SORTIE_CREATE,
    BON_SORTIE_VALIDATE,
    BON_SORTIE_CANCEL,
    BON_SORTIE_READ,
    
    USER_MANAGE,
    AUDIT_READ
}
